var fs = require("fs");
var p = ".github/workflows/baseline-pr-validation.yml";
var c = fs.readFileSync(p, "utf8");
c = c.replace(/\r\n/g, "\n");

var newJob = [
  "",
  "  path-b-migrate-resolve:",
  "    name: Path B - Migrate Resolve",
  "    runs-on: ubuntu-latest",
  "    services:",
  "      postgres:",
  "        image: postgres:16",
  "        env:",
  "          POSTGRES_USER: valtriox_test",
  "          POSTGRES_PASSWORD: valtriox_test_pass",
  "          POSTGRES_DB: valtriox_test",
  "        ports:",
  "          - 5432:5432",
  "        options: >-",
  "          --health-cmd \"pg_isready -U valtriox_test\"",
  "          --health-interval 10s",
  "          --health-timeout 5s",
  "          --health-retries 5",
  "    env:",
  "      DATABASE_URL: postgresql://valtriox_test:valtriox_test_pass@localhost:5432/valtriox_test",
  "      DIRECT_DATABASE_URL: postgresql://valtriox_test:valtriox_test_pass@localhost:5432/valtriox_test",
  "    steps:",
  "      - uses: actions/checkout@v4",
  "      - uses: actions/setup-node@v4",
  "        with:",
  "          node-version: 24",
  "      - run: npm ci",
  "      - name: Prisma generate",
  "        run: npx prisma generate",
  "      - name: Apply all migrations (Path A baseline)",
  "        run: npx prisma migrate deploy",
  "      - name: Identify and remove last migration (simulate pending)",
  "        run: |",
  "          LAST_MIGRATION=$(node -e \"",
  "            const {Pool}=require('pg');",
  "            const p=new Pool({connectionString:process.env.DATABASE_URL});",
  "            p.query('SELECT migration_name FROM _prisma_migrations ORDER BY finished_at DESC LIMIT 1')",
  "              .then(r=>{console.log(r.rows[0].migration_name);p.end();})",
  "              .catch(e=>{console.error(e);process.exit(1);});",
  "          \")",
  "          echo \"LAST_MIGRATION=$LAST_MIGRATION\" >> $GITHUB_ENV",
  "          echo \"Simulating pending migration: $LAST_MIGRATION\"",
  "          node -e \"",
  "            const {Pool}=require('pg');",
  "            const p=new Pool({connectionString:process.env.DATABASE_URL});",
  "            p.query(\\\"DELETE FROM _prisma_migrations WHERE migration_name='\\\"+process.env.LAST_MIGRATION+\\\"'\\\")",
  "              .then(()=>{console.log('Removed from history: '+process.env.LAST_MIGRATION);p.end();})",
  "              .catch(e=>{console.error(e);process.exit(1);});",
  "          \"",
  "      - name: Capture BEFORE resolve row counts",
  "        run: node scripts/baseline/ci-capture-row-counts.cjs before-resolve",
  "      - name: Execute prisma migrate resolve (Path B)",
  "        run: npx prisma migrate resolve --applied \"$LAST_MIGRATION\" --schema prisma/schema.prisma",
  "      - name: Capture AFTER resolve row counts",
  "        run: node scripts/baseline/ci-capture-row-counts.cjs after-resolve",
  "      - name: Migration history proof",
  "        run: |",
  "          node -e \"",
  "            const {Pool}=require('pg');",
  "            const p=new Pool({connectionString:process.env.DATABASE_URL});",
  "            p.query(\\\"SELECT migration_name,applied_steps_count FROM _prisma_migrations WHERE migration_name='\\\"+process.env.LAST_MIGRATION+\\\"'\\\")",
  "              .then(r=>{",
  "                if(r.rows.length===0){console.error('FATAL: migration not found after resolve');process.exit(1);}",
  "                console.log('MIGRATION HISTORY PROOF:');",
  "                console.log('  name: '+r.rows[0].migration_name);",
  "                console.log('  steps: '+r.rows[0].applied_steps_count);",
  "                p.end();",
  "              }).catch(e=>{console.error(e);process.exit(1);});",
  "          \"",
  "      - name: Compare before/after row counts",
  "        run: |",
  "          node -e \"",
  "            const fs=require('fs');",
  "            const b=JSON.parse(fs.readFileSync('backups/before-resolve-row-counts.json','utf8'));",
  "            const a=JSON.parse(fs.readFileSync('backups/after-resolve-row-counts.json','utf8'));",
  "            const bM=new Map(b.counts.map(c=>[c.table,c.rows]));",
  "            const aM=new Map(a.counts.map(c=>[c.table,c.rows]));",
  "            const all=new Set([...bM.keys(),...aM.keys()]);",
  "            let ok=true;",
  "            for(const t of all){const bv=bM.get(t)??-1;const av=aM.get(t)??-1;if(bv!==av){console.error('DELTA: '+t+' before='+bv+' after='+av);ok=false;}}",
  "            if(ok){console.log('ROW COUNT CHECK PASSED: No unexpected deltas (resolve is data-safe)');}",
  "            else{process.exit(1);}",
  "          \"",
  "      - name: Upload Path B artifacts",
  "        if: always()",
  "        uses: actions/upload-artifact@v4",
  "        with:",
  "          name: path-b-resolve-${{ github.sha }}",
  "          path: |",
  "            backups/before-resolve-row-counts.json",
  "            backups/after-resolve-row-counts.json",
  "          retention-days: 30",
].join("\n");

// Append at end of file
c = c.trimEnd() + "\n" + newJob + "\n";
fs.writeFileSync(p, c);
console.log("WORKFLOW UPDATED WITH PATH B JOB");
