// Build src/lib/brand-logo.ts from the uploaded PNG.
// Run: node scripts/build-logo-ts.js
const fs = require('fs');
const path = require('path');

const srcPng = path.join(__dirname, '..', 'public', 'valtriox-logo-vertical-inverted.png');
const b64 = fs.readFileSync(srcPng).toString('base64');

const out = [
  '// ============================================================================',
  '// Brand Logo - Valtriox - Embedded base64 of the complete logo',
  '// ============================================================================',
  '// This file is AUTO-GENERATED by scripts/build-logo-ts.js.',
  '// Source: public/valtriox-logo-vertical-inverted.png (1209x999, RGB)',
  '//',
  '// The logo is embedded as a base64 data URI so it works on Vercel serverless',
  '// without any filesystem dependency. It is used as the primary brand mark on',
  '// reports, proposals, lead magnets, invoices and invitation documents. The',
  '// complete wordmark is used instead of the old icon-only fallback.',
  '// ============================================================================',
  '',
  '// PNG mime type, base64-encoded payload',
  'export const BRAND_LOGO_DATA_URI = "data:image/png;base64,' + b64 + '";',
  '',
  'let _brandLogoBuffer: Buffer | null | undefined;',
  '',
  '/**',
  ' * Returns the brand logo as a Node Buffer (cached after first call).',
  ' * Returns null only if base64 decoding fails (should never happen).',
  ' */',
  'export function getBrandLogoBuffer(): Buffer | null {',
  '  if (_brandLogoBuffer !== undefined) return _brandLogoBuffer;',
  '  try {',
  '    const b64 = BRAND_LOGO_DATA_URI.split(\',\')[1];',
  '    _brandLogoBuffer = b64 ? Buffer.from(b64, \'base64\') : null;',
  '  } catch {',
  '    _brandLogoBuffer = null;',
  '  }',
  '  return _brandLogoBuffer;',
  '}',
  '',
  '/**',
  ' * Source dimensions of the brand logo PNG (used to preserve aspect ratio).',
  ' * Source: 1209 x 999 (height/width ratio about 0.826).',
  ' */',
  'export const BRAND_LOGO_SOURCE_W = 1209;',
  'export const BRAND_LOGO_SOURCE_H = 999;',
  'export const BRAND_LOGO_ASPECT = BRAND_LOGO_SOURCE_H / BRAND_LOGO_SOURCE_W; // ~0.826',
  ''
].join('\n');

fs.writeFileSync(path.join('src', 'lib', 'brand-logo.ts'), out);
console.log('Wrote src/lib/brand-logo.ts', fs.statSync('src/lib/brand-logo.ts').size, 'bytes');
